"""empty message

Revision ID: 02a0f9e5db90
Revises: e60f69c9cc16
Create Date: 2021-12-14 14:58:43.073393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a0f9e5db90'
down_revision = 'e60f69c9cc16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_ibfk_1', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'salon', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_ibfk_1', 'employees', 'plants', ['department_id'], ['id'])
    # ### end Alembic commands ###
