"""empty message

Revision ID: ef4cf200ee25
Revises: 
Create Date: 2021-11-17 15:10:52.168143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef4cf200ee25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salon', sa.Column('director_id', sa.Integer(), nullable=False))
    op.add_column('salon', sa.Column('city', sa.String(length=255), nullable=False))
    op.add_column('salon', sa.Column('address', sa.String(length=255), nullable=False))
    op.drop_index('email', table_name='salon')
    op.drop_column('salon', 'email')
    op.drop_column('salon', 'department_type')
    op.drop_column('salon', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salon', sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('salon', sa.Column('department_type', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('salon', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.create_index('email', 'salon', ['email'], unique=False)
    op.drop_column('salon', 'address')
    op.drop_column('salon', 'city')
    op.drop_column('salon', 'director_id')
    # ### end Alembic commands ###
