# Generated by Django 3.1.7 on 2021-12-28 18:20

from django.db import migrations, models
import src.apps.ban_for_ip.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('expire_date', models.DateTimeField(default=src.apps.ban_for_ip.utils.default_ban_time)),
            ],
        ),
    ]
