"""empty message

Revision ID: 342be7bec411
Revises: 44561631816b
Create Date: 2021-12-28 15:58:28.082271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342be7bec411'
down_revision = '44561631816b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'password')
    # ### end Alembic commands ###
